# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               teisam.net
tagline:             'det kan jo hende at noen fornuftige ord kommer her'
description:         'Om jeg får ånden over meg og vil lire av meg litt mer enn hva jeg gjør på <a href="https://twitter.com/teisam" target="_blank">@teisam</a>.'
url:                 http://teisam.net
baseurl:             ''
paginate:            5